server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # SPA (React) yönlendirmesi - sayfa yenilendiğinde 404 vermesini engeller
        try_files $uri $uri/ /index.html;
    }
}
